name: CRED
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55867
title: 'CRAFTING SERVICES THAT ENCHANT, EMPOWER AND INSPIRE SINCE 2015 ©'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefc01'
    - '#ffffff'
    - '#000000'
    - '#52575e'
    - '#b1b2b2'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
